local telescope = require('telescope.builtin')

vim.keymap.set('n', '<leader>ff', telescope.find_files)
vim.keymap.set('n', '<leader>fg', telescope.live_grep)
vim.keymap.set('n', '<leader>fb', telescope.buffers)
vim.keymap.set('n', '<leader>fq', telescope.quickfix)
vim.keymap.set('n', '<leader>fl', telescope.loclist)
vim.keymap.set('n', '<leader>fd', telescope.diagnostics)
vim.keymap.set('n', '<leader>fr', telescope.lsp_references)
vim.keymap.set('n', '<leader>fi', telescope.lsp_implementations)
vim.keymap.set('n', '<leader>ft', telescope.tags)
vim.keymap.set('n', '<leader>fh', telescope.help_tags)
vim.keymap.set('n', '<leader>fm', telescope.keymaps)
