add_newline = false

prompt_order = [
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "battery",
    "character",
]

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
unknown_symbol = ""
empty_symbol = ""
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[character]
symbol = "$"
error_symbol = "$"
vicmd_symbol = "|"
style_success = "white"
style_failure = "red"

[directory]
style = "bold blue"

[git_branch]
symbol = ""
style = "bold purple"

[git_state]
style = "bold purple"

[git_status]
style = "bold purple"
