#!/bin/sh

limelight -m config width            2
limelight -m config radius           9
limelight -m config placement        inset
limelight -m config active_color     0xff458588
limelight -m config normal_color     0x00ffffff

echo "limelight configuration loaded.."
