#!/bin/sh

# auto balance windows
yabai -m config layout bsp
yabai -m config auto_balance on

# padding between windows
yabai -m config window_gap 2

# border
yabai -m config window_border              on
yabai -m config window_border_hidpi        on
yabai -m config window_border_width        2
yabai -m config window_border_radius       11
yabai -m config active_window_border_color 0xff8ec07c
yabai -m config normal_window_border_color 0xff727272

# applications to ignore
yabai -m rule --add app="Finder"             manage=off
yabai -m rule --add app="Docker Desktop"     manage=off
yabai -m rule --add app="System Preferences" manage=off

# source work config
[ -r ~/jobfiles/macos/yabai/yabairc ] && source ~/jobfiles/macos/yabai/yabairc

echo "yabai configuration loaded.."
