# start aerospace at login
start-at-login = true

# the 'accordion-padding' specifies the size of accordion padding
accordion-padding = 40

# gaps between windows and between monitor edges
[gaps]
    inner.horizontal = [{ monitor."lg" = 12 }, 0]
    inner.vertical =   [{ monitor."lg" = 12 }, 0]
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

# keybindings
[mode.main.binding]

    # open the terminal
    shift-ctrl-alt-cmd-enter = 'exec-and-forget /opt/homebrew/bin/kitty'

    # minimize the current window
    shift-ctrl-alt-q = 'macos-native-minimize'

    # toggle zoom
    shift-ctrl-alt-z = 'fullscreen'

    # toggle float
    shift-ctrl-alt-cmd-z = 'layout floating tiling'

    # toggle split type
    shift-ctrl-alt-g = 'layout tiles horizontal vertical'

    # toggle accordian type
    shift-ctrl-alt-cmd-g = 'layout accordion horizontal vertical'

    # balance size of windows
    shift-ctrl-alt-b = 'balance-sizes'

    # move focus to adjacent monitor
    shift-ctrl-alt-u = 'focus-monitor prev'
    shift-ctrl-alt-y = 'focus-monitor next'

    # move window to adjacent monitor
    shift-ctrl-alt-cmd-u = 'move-node-to-monitor prev'
    shift-ctrl-alt-cmd-y = 'move-node-to-monitor next'

    # resize window
    shift-ctrl-alt-h = 'resize width -100'
    shift-ctrl-alt-j = 'resize height +100'
    shift-ctrl-alt-k = 'resize height -100'
    shift-ctrl-alt-l = 'resize width +100'

    # focus adjacent workspacec
    shift-ctrl-alt-leftSquareBracket = 'workspace prev'
    shift-ctrl-alt-rightSquareBracket = 'workspace next'

    # switch to the previously focused workspace
    shift-ctrl-alt-a = 'workspace-back-and-forth'

    # focus an adjacent window
    shift-ctrl-alt-n = 'focus left'
    shift-ctrl-alt-e = 'focus down'
    shift-ctrl-alt-i = 'focus up'
    shift-ctrl-alt-o = 'focus right'

    # swap a window
    shift-ctrl-alt-cmd-n = 'move left'
    shift-ctrl-alt-cmd-e = 'move down'
    shift-ctrl-alt-cmd-i = 'move up'
    shift-ctrl-alt-cmd-o = 'move right'

    # focus a specific workspace
    shift-ctrl-alt-x = 'workspace 1'
    shift-ctrl-alt-c = 'workspace 2'
    shift-ctrl-alt-d = 'workspace 3'
    shift-ctrl-alt-r = 'workspace 4'
    shift-ctrl-alt-s = 'workspace 5'
    shift-ctrl-alt-t = 'workspace 6'
    shift-ctrl-alt-w = 'workspace 7'
    shift-ctrl-alt-f = 'workspace 8'
    shift-ctrl-alt-p = 'workspace 9'

    # move window to specific workspace
    shift-ctrl-alt-cmd-x = 'move-node-to-workspace 1'
    shift-ctrl-alt-cmd-c = 'move-node-to-workspace 2'
    shift-ctrl-alt-cmd-d = 'move-node-to-workspace 3'
    shift-ctrl-alt-cmd-r = 'move-node-to-workspace 4'
    shift-ctrl-alt-cmd-s = 'move-node-to-workspace 5'
    shift-ctrl-alt-cmd-t = 'move-node-to-workspace 6'
    shift-ctrl-alt-cmd-w = 'move-node-to-workspace 7'
    shift-ctrl-alt-cmd-f = 'move-node-to-workspace 8'
    shift-ctrl-alt-cmd-p = 'move-node-to-workspace 9'
