#!/bin/bash

# path="$@"
# parents=""
#
# dots=$(echo "$path" | cut -d '/' -f1)
# if [[ "$dots" =~ ^[..]+$ ]]; then
#   echo "YES"
# fi
# echo "$dots"
# i=${#dots}
# while [[ $i -gt 1 ]]; do
#   parents+="../"
#   i=$((i-1))
# done
# newpath="$parents${path#"$dots"}"
# echo "$newpath"
#
# path="..../my/dir"
# echo "$path" | 
