#!/usr/bin/env sh

limelight -m config width            1
limelight -m config radius           9
limelight -m config placement        internal
limelight -m config active_color     0xffb9bfca
limelight -m config normal_color     0x00ffffff

echo "limelight configuration loaded.."
