# TODO: zshenv might be sourced twice (by tmux?).. Not exactly sure since zsh -x" prints `echo hi` twice but everything else once

# alternative to the slower `eval "$(/opt/homebrew/bin/brew shellenv)`
if [[ $OSTYPE =~ "darwin"* ]]; then
  export HOMEBREW_PREFIX="/opt/homebrew"
  export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
  export HOMEBREW_REPOSITORY="/opt/homebrew"
  export HOMEBREW_NO_AUTO_UPDATE="true"
fi

# set help directory for zsh built-ins
if [[ $OSTYPE =~ "darwin"* ]]; then
  export HELPDIR="$HOMEBREW_PREFIX/share/zsh/help"
else
  export HELPDIR="/usr/share/zsh/$ZSH_VERSION/help"
fi

# set the preferred editor to neovim if not already set
if [ -z $EDITOR ]; then
  export EDITOR="nvim"
fi
if [ -z $VISUAL ]; then
  export VISUAL="nvim"
fi

# set to the path of the tty device for gpg
export GPG_TTY=$(tty)

# less options
export LESS="--RAW-CONTROL-CHARS --LONG-PROMPT --ignore-case --jump-target=5"

# do not paginate awscli responses
export AWS_PAGER=""

# match jq colors to vim
export JQ_COLORS="0;37:0;37:0;37:0;37:0;37:0;37:0;37:0;36"

# kubectx / kubens colors
export KUBECTX_CURRENT_FGCOLOR=$(tput setaf 5)
export KUBECTX_CURRENT_BGCOLOR=$(tput setaf 5)

# fzf flags and colors
export FZF_DEFAULT_COMMAND="fd -H -I --strip-cwd-prefix --type file --exclude tags --exclude '*.tags' --exclude .git --exclude vendor --exclude node_modules --exclude package/opt --exclude package/start --exclude tmux/plugins"
export FZF_ALT_C_COMMAND="fd -H -I --strip-cwd-prefix --type directory --exclude tags --exclude '*.tags' --exclude .git --exclude vendor --exclude node_modules --exclude package/opt --exclude package/start --exclude tmux/plugins"
export FZF_CTRL_T_COMMAND="fd -H -I --strip-cwd-prefix --exclude tags --exclude '*.tags' --exclude .git --exclude vendor --exclude node_modules --exclude package/opt --exclude package/start --exclude tmux/plugins"
export FZF_DEFAULT_OPTS="--multi --inline-info --height=60% --marker=+ --border=horizontal \
--color border:8 \
--color bg+:13 \
--color fg+:7:regular \
--color gutter:-1 \
--color header:8 \
--color hl:1:bold \
--color hl+:1:bold \
--color info:8 \
--color marker:2:regular \
--color spinner:7 \
--color pointer:4:regular \
--color prompt:7:regular \
--color query:7:regular"

# source work zshenv
if [ -r ~/jobfiles/zsh/zshenv ]; then
  source ~/jobfiles/zsh/zshenv
fi
