# vim: set filetype=bash:

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# start tmux on shell login, attaching to (or creating a) session 'dotfiles'
[[ -z "$TMUX" ]] && tmux new-session -A -s dotfiles

# match typed command and arguments when moving through history
bind '"\C-p": history-search-backward'
bind '"\C-n": history-search-forward'

# disable suspending terminal with ctrl-s
stty -ixon

# make tab completion case insensitive
bind 'set completion-ignore-case on'

# shopt settings
shopt -s autocd
shopt -s cdspell
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dotglob
shopt -s histappend
shopt -s histverify
shopt -s globstar

# print current working directory in prompt
PS1="\[\e[0;34m\]\w\[\e[0;00m\] \$ "

# shorten the path in the prompt to three directories
PROMPT_DIRTRIM=3

# history
HISTSIZE=5000            # number of lines/commands stored in memory
HISTFILESIZE=10000       # number of lines/commands stored in the history file
HISTTIMEFORMAT="%F %T  " # add the execution time to commands in the hist file

# ignore subsequent, duplicate lines; erase previous matching lines;
# ignore lines starting with a whitespace character
HISTCONTROL=ignoreboth:erasedups

# update history after every command
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# environment variables
export GPG_TTY=$(tty)            # set to the path of the tty device for gpg
export MANPAGER='less -s -M +Gg' # prompt percent into file
export AWS_PAGER=''              # do not paginate awscli responses
export GOPATH=$HOME/go           # set GOPATH
export PATH=$GOPATH/bin:$PATH    # add GOPATH to PATH
export KUBECTX_IGNORE_FZF=1      # kubectx prints to stout instead of fzf

# set the preferred editor to nvim (without plugins) if not already set
[[ -z "$VISUAL" ]] && export VISUAL='nvim --noplugin'

# add ~/.local/bin to path if it doesn't already exist
[[ ! "$PATH" == *$HOME/.local/bin* ]] && export PATH=$HOME/.local/bin:$PATH

# fzf
export FZF_DEFAULT_OPTS='--inline-info --border'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --no-ignore --exclude .git/ \
    --exclude vendor/ --exclude node_modules/'


# refresh watch every second
alias watch='watch -n 1 '

# cd
alias     ..='cd ..'
alias    ...='cd ../..'
alias   ....='cd ../../..'
alias  .....='cd ../../../..'
alias ......='cd ../../../../..'

# ls
alias  l='ls -lah'
alias ll='ls -lh'
alias ls='ls -G'

# colorize grep
alias  grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# kubernetes
alias    k='kubectl'
alias kctx='kubectx'
alias  kns='kubens'

# git
alias   g='git'
alias  ga='git add'
alias  gb='git branch'
alias  gc='git commit'
alias gcl='git clone'
alias gco='git checkout'
alias  gd='git diff'
alias  gf='git fetch'
alias  gl='git log'
alias  gm='git merge'
alias  gp='git pull'
alias gpu='git push'
alias  gr='git reset'
alias grb='git rebase'
alias grm='git remote'
alias  gs='git status'
alias gst='git stash'
alias gsh='git show'


# fzf key bindings
[[ -r "/usr/local/opt/fzf/shell/key-bindings.bash" ]] && \
    source "/usr/local/opt/fzf/shell/key-bindings.bash"
[[ -r "/usr/share/fzf/shell/key-bindings.bash" ]] && \
    source "/usr/share/fzf/shell/key-bindings.bash"

# completion
[[ -r "/usr/local/bin/aws_completer" ]] && \
    complete -C "/usr/local/bin/aws_completer" aws
[[ -r "/usr/local/bin/git-completion.bash" ]] && \
    source "/usr/local/bin/git-completion.bash"
[[ -r "/usr/local/opt/fzf/shell/completion.bash" ]] && \
    source "/usr/local/opt/fzf/shell/completion.bash"
[[ -r "/usr/share/fzf/shell/completion.bash" ]] && \
    source "/usr/share/fzf/shell/completion.bash"

# NOTE: this file takes 0.2 seconds to load
# alias completion (source after alias/completion configs)
[[ -r "$HOME/dotfiles/bash/alias-completion.bash" ]] && \
    source "$HOME/dotfiles/bash/alias-completion.bash"


# kubectl completion lazy loading
kubectl() {
    unset -f kubectl
    source <(kubectl completion bash)
    kubectl "$@"
}

# nvim alias with support for nested nvim sessions
e() {
    if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
        nvim --server $NVIM_LISTEN_ADDRESS --remote "$@"
    else
        nvim "$@"
    fi
}

# qmk compile/flash commands
qmk() {
    case $@ in
        'compile iris')
            command qmk compile -kb keebio/iris/rev4 -km anordhoff
            ;;
        'flash iris')
            command qmk flash -kb keebio/iris/rev4 -km anordhoff
            ;;
        'compile yd60')
            command qmk compile -kb yd60mq/16led -km anordhoff
            ;;
        'flash yd60')
            command qmk flash -kb yd60mq/16led -km anordhoff
            ;;
        *)
            command qmk "$@"
            ;;
    esac
}


# source work bashrc
[[ -r ~/jobfiles/bash/bashrc ]] && source ~/jobfiles/bash/bashrc
